### ISSUE TITLE
Is it possible to merge multiple ply file?

### ISSUE THREAD

**Issue by renwanggtv** [btsmart/splatt3r#16]
This project is awsome, but when I try to merge multiple ply file from multiple image, the result is not good. I was just wondering is it possible to add more image as input? Or is there a better way to merge multiple ply file, I tried Deep Closest Point and PointNetLK, the result from both method are bad

**Comment by btsmart** [comment]
Hello,

I have not personally attempted to merge multiple .ply files, so I am not sure what the best methodology would be. I would be keen to know if you come across something that works well. If your primary issue is that the point clouds don't align well and you have not tried it yet, I would consider trying MASt3R's global alignment for point clouds.

There is currently no way to add more than two images as input, and I think the best way to do this will be a topic of future research. There is some more information about this in Issues https://github.com/btsmart/splatt3r/issues/7 and https://github.com/btsmart/splatt3r/issues/13. In particular they have some information about why I think naively combining .ply files might not work well.
