### ISSUE TITLE
About inference image size

### ISSUE THREAD

**Issue by wuqun-tju** [btsmart/splatt3r#22]
Hello， when I run demo， I found that image size will be cropped square,  can I modify it, Because I need retain overlap area  of two images, and square will crop two much.

**Comment by btsmart** [comment]
Hello,

Our model was only trained with square, 512x512 resolution images, so our demo code also crops input images to this resolution/aspect ratio. If you run the demo locally, you should be able to change the cropping code to support your desired resolutions, although you might need to make sure that the patch embedding works with your chosen resolution. I am unsure how well our model will generalize to these cases though, so you may need to finetune our model.
