### ISSUE TITLE
World coordinates

### ISSUE THREAD

**Issue by bfialkoff** [btsmart/splatt3r#24]
Given the camera calibrations for the images, is there a way to recover the world coordinates of the reconstructed point cloud?

**Comment by btsmart** [comment]
Hello @bfialkoff,

Like MASt3R, we predict our point cloud in the coordinate space of the first image (as we don't know where it is in space). If this is sufficient for your use case, you should be able to take the union of `pred1['pts3d']` and `pred2['pts3d_in_other_view']` as the point cloud (or alternatively the union of `pred1['means']` and `pred2['means_in_other_view']`  if you want the means of the Gaussians).

If I understand your question correctly, you are asking if you are able to convert from the point cloud from being in the first image's coordinate space to the world space if you know the ground truth position of the first image. I have not done this with our code, but in principle you should be able to use the camera pose to obtain a camera to world transformation matrix, and then multiply the positions of all the points by this matrix. You may wish to look at the [MASt3R repo](https://github.com/naver/mast3r), which has some more examples of manipulating the point cloud produced by MASt3R (such as by using performing global alignment when more than two images are present).

Let me know if this helps!

**Comment by bfialkoff** [comment]
Hey thanks for your response. 

I meant that images were captured with calibrated cameras. I assume that can help me... 

"in the coordinate frame of the first image" that means you treat the first image as if it is aligned with the z-axis (Extrinsics are Identity)? 

I will look into this and try to figure it out. 

Thanks!

**Comment by btsmart** [comment]
Yes exactly, the extrinsics of the first image are treated like the identity.

If you have the extrinsics/intrinsics of both of your images, you might also want to examine [PixelSplat](https://davidcharatan.com/pixelsplat/) or [MVSplat](https://donydchen.github.io/mvsplat/), which are both able to take advantage of the known camera parameters (whereas our method isn't really able to use known camera parameters during prediction).
