### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by miaolin968** [btsmart/splatt3r#26]
Is depth information used during training?

**Comment by btsmart** [comment]
Hello @miaolin968,

Yes, during training we use ground truth depth information and camera poses to supervise our reconstructions. If you have access to camera poses but not depth, you may wish to check out other methods such as [PixelSplat](https://davidcharatan.com/pixelsplat/) and [MVSplat](https://donydchen.github.io/mvsplat/), which introduce methods for handling the lack of depth.
