### ISSUE TITLE
 ScanNet++ Depth Images Issue

### ISSUE THREAD

**Issue by StephenYangjz** [btsmart/splatt3r#27]
Greetings,

Hope all is well!

We are using ScanNet++ for a research project (access granted) but encountering an issue with OpenGL with our lab's cluster, and we are probably unable to resolve it to render the depth images.

We are wondering if by any chance you can help send us the render_depth folder for each scene? It would greatly help us and others in the community with similar issues!

```
output_dir/SCENE_ID/[dslr, iphone]
├── render_rgb
└── render_depth
```

Thank you so much, and we look forward to hearing from you.

**Comment by miaolin968** [comment]
I meet same problem when render render_depth.
`RuntimeError: Failed to initialize EGL`
I would be grateful if you would like to help

**Comment by btsmart** [comment]
Hello @StephenYangjz and @miaolin968,

Sorry for the delay in replying, I have been very sick and busy over the past few weeks.

Regarding the issues with rendering the depth, such as the OpenGL issues and the failure to initialize EGL, unfortunately I don't think I am able to help. I used SplaTAM's version of the [ScanNet++ toolkit](https://github.com/Nik-V9/scannetpp) to render depth, so you may wish to raise issues there, or with the original ScanNet++ toolkit authors.

My understanding of the [ScanNet++ license](https://kaldir.vc.in.tum.de/scannetpp/static/scannetpp-terms-of-use.pdf) is that I am only able to share my processed images with academic colleagues if they have signed the license agreement. I will need to double check that I can share the data in this case, but if you have signed the license and are still interested in my data I am happy to share a copy. You can reach out to me through my email listed in the ArXiv paper.
