### ISSUE TITLE
How to train on other datasets?

### ISSUE THREAD

**Issue by YHChen0511** [btsmart/splatt3r#31]
How to train on other datasets such as re10k, acid or my own customed dataset?

**Comment by brandonsmartdev** [comment]
Hello @YHChen0511,

If you would like to train with your own dataset, you can create a copy of [data/scannetpp/scannetpp.py](https://github.com/btsmart/splatt3r/blob/main/data/scannetpp/scannetpp.py) for your new dataset, modifying the `ScanNetPPData` class as well as the `get_scannet_dataset()` and `get_scannet_dataset()` methods, and then modifying the calls to `get_scannet_dataset()` and `get_scannet_test_dataset()` in `main.py`. For your new dataset, if you wish to follow the sampling strategy we use in the paper, you will need to generate your own coverage files (see [here](https://github.com/btsmart/splatt3r/issues/18#issuecomment-2351682562)).

Regarding Re10k and ACID, our method relies on ground truth depth data during training, and poses for training and testing that are in metric scale, so Re10k and ACID cannot be directly used. You may wish to look into other methods which are able to work with these datasets, such as [NoPoSplat](https://noposplat.github.io/) and [PF3Splat](https://cvlab-kaist.github.io/PF3plat/).
