### ISSUE TITLE
problem of camera pose

### ISSUE THREAD

**Issue by miaolin968** [btsmart/splatt3r#33]
Dear author:
Thank you to the author for open-sourcing such a great work.  
I have a question regarding the code. I believe this is a pose-free method, but around line 97 in `scannet.py`, you use the `transform_matrix` data. Is this data the camera extrinsic parameters?

**Comment by btsmart** [comment]
Hello @miaolin968,

Our method is not pose-free during training, only at inference time once the model has been trained. During training we use ground truth camera poses and depth for supervision, and when calculating metrics during evaluation we use ground truth camera poses to calculate where to render our scenes from. However once trained, the model can be used without camera poses.

`transform_matrix` does indeed refer to the camera intrinsic parameters. If you would like to use a dataset that does not have camera poses, you may need to modify the dataloaders and evaluation procedures so they are not needed.

**Comment by miaolin968** [comment]
Thank you for your reply! My issue has been resolved.
