### ISSUE TITLE
Paper link not working

### ISSUE THREAD

**Issue by JoeriHermans** [btsmart/splatt3r#5]
Just an FYI, the paper links on both the project page and the README do not seem to work. 🥲 Or, since I can't seem to find anything through Google, you're still awaiting the final ArXiv link. In that case, I'll wait :)

**Comment by btsmart** [comment]
Hello! Yes the ArXiv links are just a placeholder at the moment. We are currently waiting for the ArXiv submission to be made public, and we hadn't expected this repo to get so much attention the meantime!
